# Generated by Django 5.0.6 on 2024-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
