# Generated by Django 5.0.6 on 2024-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_admin_user_is_staff_user_is_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
