# Generated by Django 5.0.6 on 2024-07-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_job_client_remove_instructor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
