# Generated by Django 5.0.6 on 2024-07-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='staff',
        ),
    ]
