# Generated by Django 5.0.6 on 2024-07-10 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_user_category_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills_to_gain',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='topics',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
