# Generated by Django 5.0.6 on 2024-07-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_course_category_course_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.URLField(null=True),
        ),
    ]
